### PR TITLE
Initial Casadi merge

### PR DESCRIPTION
**Pull request by pariterre**

### CODE REVIEW

**Comment by ju6ge** [comment]
Hey Benjamin,

so my initial merge proposal that would make rbdl-casadi a renamed library that can be installed on the system in parallel with the eigen version is available on the casadi branach of my [rbdl-orb fork](https://github.com/ju6ge/rbdl-orb). I wanted to push these updates to the PR, but could not. Can you take a look an merge them?

I am also interested to know if this will work with you downstream setup. I added a RBDLCasadiConfig.cmake to make it possible to select which rbdl version to use in cmake by either using "FIND_PACKAGE(RBDL)" or "FIND_PACKAGE(RBDLCasadi)".

**Comment by pariterre** [comment]
@ju6ge 
Can you open a PR to my fork, so I know what you changed?

`FIND_PACKAGE(RBDLCasadi)` feels weird. I would suggest: `FIND_PACKAGE(RBDL Eigen)` or `FIND_PACKAGE(RBDL Casadi)` with `FIND_PACKAGE(RBDL)` being the default for Eigen

**Comment by ju6ge** [comment]
I sent you a PR, most of the commits are about the Windows support for RBDL, which I am working on in parallel and has already been merged to rbdl-orb master.

I will look into updating the selection method, doing with a separate cmake files was easier for the moment.

**Comment by pariterre** [comment]
@ju6ge 
Hi Felix, I just ping you since you seem to have forgotten to merge this PR. It makes Casadi fully work including with conda-forge
Thanks!

**Comment by ju6ge** [comment]
Hey, not completely I have had another update and sent a PR to your to your fork. I added some documentation and some example code. But the example is not fully working, and since i am not that familiar with casadi it would be great to get your input. Would you be able to do a final meetup so we can finalize this PR?

**Pull request merged**
