### PR TITLE
URDF Update

### PR DESCRIPTION
**Pull request by ju6ge**
From the code of the urdf addon it is quite obvious that it was created in a hurry and it has some big problems. This PR aims to address the biggest ones, by replacing the urdfparser library with a parser that gives us error handling and also implements error handling for the rbdl addon itself. It also removes some assumptions that where build in to the parsing logic that do not hold true for very simple models.

With these changes i get more sensible results for simple urdf models when visualized with rbdl-toolkit. This does not need to get merged immediately and i might still update this if i find more things need to be addressed in order to handle more complicated models that do more complex things with the joint origins.

### CODE REVIEW

**Comment by ju6ge** [comment]
Trigger jenkins?

**Review by mjhmilla — CHANGES_REQUESTED** [review]
I just started the process of building rbdl on my machine and CMake complains:

"
 CMake Error at addons/urdfreader/thirdparty/CMakeLists.txt:1 (ADD_SUBDIRECTORY):
   The source directory
     /home/mjhmilla/dev/orbGitHubCodeReview/rbdl-orb/addons/urdfreader/thirdparty/urdfparser
   does not contain a CMakeLists.txt file.
"

I then read the README.md file within the URDF addon, but this wasn't very helpful. Have I missed a critical instruction somewhere?

**Comment by ju6ge** [comment]
Oh well the urdfreader code is now included as a git submodule. So that means you need to recursively clone the code. Or use ```git submodule init && git submodule update``` after the pull. I think I should update the readme to reflect this change because up until now rbdl-orb has not been using submodules.

**Comment by mjhmilla** [comment]
Progress is being made, but there are still a few things to update:

1. When CMake fails to find the urdfreader a message should be written to the screen directing the reader to the README.md file. Right now the message is a bit opaque:

"
CMake Error at addons/urdfreader/thirdparty/CMakeLists.txt:1 (ADD_SUBDIRECTORY):
The source directory
/home/mjhmilla/dev/orbGitHubCodeReview/rbdl-orb/addons/urdfreader/thirdparty/urdfparser
does not contain a CMakeLists.txt file.
"

2. READE.md text updates:
a. Change 
  "If you missed doing that you can intialize the submodules after the fact with" 
  to 
  "If you missed doing that you can initialize the submodules (from a terminal within the source directory) after the fact with"
  
  This edit is not for you or I, but for people who are both new to git and to RBDL.
  
b.  Line 163 "Build" is spelled incorrectly. Run a spell checker on the entire README.md

3. I used 
  git submodule init
  git submodule update
  
  and CMake complains about not being able to find Catch2 (message below). This needs to be addressed somehow - either Catch2 needs to be included in the recursive clone with a FindCatch2.cmake file, or the README.md documentation needs to be updated + a message added to the main CMake file that refers the person to the README.md file if Catch2 isn't found. 
  
For the longevity of the code I suggest you pick an option that is as easy for the person using this code as possible: add Catch2 to the recursive clone, add a FindCatch2.cmake file, and add an entry to the README.md file.
 
 " 
   CMake Error at addons/urdfreader/thirdparty/urdfparser/CMakeLists.txt:35 (FIND_PACKAGE):
   By not providing "FindCatch2.cmake" in CMAKE_MODULE_PATH this project has
   asked CMake to find a package configuration file provided by "Catch2", but
   CMake did not find one.

   Could not find a package configuration file provided by "Catch2" with any
   of the following names:

     Catch2Config.cmake
     catch2-config.cmake

   Add the installation prefix of "Catch2" to CMAKE_PREFIX_PATH or set
   "Catch2_DIR" to a directory containing one of the above files.  If "Catch2"
   provides a separate development package or SDK, be sure it has been
   installed.
"

**Comment by ju6ge** [comment]
So I went through the Readme and fixed the typos as well as some more typos that the spell checker found.

Regarding the Catch2 Error, this actually only happens when enabling the option URDF_BUILD_TEST. This option is provided by the URDF_Parser library and is just intended to be used when directly developing that library. It is not required for rbdl to run these test as well. Maybe there is an CMake option to omit certain options if we wanted to make this more clear.
Another thing to consider is that migrating all the test to Catch2 is planned for the other rbdl repository so then Catch2 would also be required anyway! And the migration is a really good idea, because Catch2 provides more output formats for the test, which enables that CI can parse and display the results with more information!

The other point of having a better error message when the submodule is missing requires some more CMake code, sadly there is no build in way to handle a failing subdirectory command with a better message, so it requires some more logic, but it should be doable.

**Comment by mjhmilla** [comment]
0. Overview question: what have you touched in addons/urdfreader and what remains the same? In other words, what exactly should i be reviewing? I'll proceed as if you've touched everything excluding what's in 'thirdparty'.

1. The main RBDL README.md should contain some instructions on how/where to get Catch2. This is not an issue for me, but new comers to RBDL might be a bit lost.

2. I can build rbdl successfully as long as I do not build the URDF test. If I build the URDF test then CMake throws an error:

CMake Error at addons/urdfreader/thirdparty/urdfparser/CMakeLists.txt:36 (ADD_EXECUTABLE):
   The target name "test" is reserved or not valid for certain CMake features,
   such as generator expressions, and may result in undefined behaviour.

CMake Error at addons/urdfreader/thirdparty/urdfparser/CMakeLists.txt:37 (TARGET_LINK_LIBRARIES):
 Cannot specify link libraries for target "test" which is not built by this
 project.


3. Update rbdl-orb/addons/urdfreader/README.md: I don't see your name listed, and I don't see any notes on the updates that you've added.

4. The test case in addons/urdfreader/thirdparty/urdfparser/test/parse_simple.cpp doesn't do much. It would be much better to have something a bit more comprehensive.

5. Formatting stuff:
a. doxygen required:
urdfreader.h:

b. Lines exceed 80 chars: 
urdfreader.h
urdfreader.cc
rbdl_urdfreader_utils.cc

**Comment by mjhmilla** [comment]
0. Overview question: what have you touched in addons/urdfreader and what remains the same? In other words, what exactly should i be reviewing? I'll proceed as if you've touched everything excluding what's in 'thirdparty'.

1. The main RBDL README.md should contain some instructions on how/where to get Catch2. This is not an issue for me, but new comers to RBDL might be a bit lost.

2. I can build rbdl successfully as long as I do not build the URDF test. If I build the URDF test then CMake throws an error:

CMake Error at addons/urdfreader/thirdparty/urdfparser/CMakeLists.txt:36 (ADD_EXECUTABLE):
   The target name "test" is reserved or not valid for certain CMake features,
   such as generator expressions, and may result in undefined behaviour.

CMake Error at addons/urdfreader/thirdparty/urdfparser/CMakeLists.txt:37 (TARGET_LINK_LIBRARIES):
 Cannot specify link libraries for target "test" which is not built by this
 project.


3. Update rbdl-orb/addons/urdfreader/README.md: I don't see your name listed, and I don't see any notes on the updates that you've added.

4. The test case in addons/urdfreader/thirdparty/urdfparser/test/parse_simple.cpp doesn't do much. It would be much better to have something a bit more comprehensive.

5. Formatting stuff:
a. doxygen required:
urdfreader.h:

b. Lines exceed 80 chars: 
urdfreader.h
urdfreader.cc
rbdl_urdfreader_utils.cc

**Comment by mjhmilla** [comment]
Hey Felix,
I accidentally hit 'close'. So now I've re-opened the pull request. Sorry for the confusion : ).

**Comment by mjhmilla** [comment]
Hey Felix,
I accidentally hit 'close'. So now I've re-opened the pull request. Sorry for the confusion : ).

**Comment by mjhmilla** [comment]
Referring to the last round of comments:
0. The main contribution that needs reviewing is everything in addons/urdfreader/thirdparty/urdfparser/src (outside of tinyxml ..)? Is that correct?
1. I see the instructions - thanks. 
2. When building with URDF_BUILD_TEST enabled I now get this error:

/home/mjhmilla/dev/orbGitHubCodeReview/rbdl-orb/addons/urdfreader/thirdparty/urdfparser/test/parse_simple.cpp:2:10: fatal error: catch2/catch.hpp: No such file or directory
 #include "catch2/catch.hpp"

a. Initially I thought this might be because I built and installed Catch2 locally (as I always do). So I build Catch2 and installed it system wide as the README.md file now suggests. But I still receive this message.
b. Then I thought that perhaps CMAKE isn't looking in /usr/local/include because it's not on my path. Nope, I still receive the failure.
c. After looking in /usr/local/include/catch2 I see the problem: there is no file called 'catch.hpp'. There is a "catch_all.hpp". I've cloned Catch2 from the same repository as is (now) listed in the README.md file. Has Catch2 renamed its header files since you last built and installed it?

3. I'm glad to see your name in the urdfreader/README.md file. Put your name and the date in the thirdparty/urdfreader/README.md file (assuming the statement I wrote in point 0.) is correct.

4. That's a much better test, thank you. In principle it would be best to have a mechanism that has all types of joints that URDF supports, but for now, this is a lot better than what was in place. 

5. 
a. I see the doxygen and it compiles nicely. Add a line to URDFReadFromString mentioning that an example can be found in /addons/urdfreader/thirdparty/urdfparser/test/parse_simple.cpp. Also: if there are any parts of the URDF spec that are not implemented, please mention those. If you don't know this off hand, maybe ask Felix Aller if he knows. I don't know this offhand as I don't use URDF for my work. 
b. Yep 80 characters. Thanks

**Comment by ju6ge** [comment]
So I have now updated the references of Catch2 to the correct branch and also enabled the urdfparser tests when running automatic testing. This should address all points we discussed last week. I will merge this PR in due course.

**Pull request merged**
