### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by ju6ge**
This pull request introduces error handling to the RBDL core library and all current addons. This was done to make RBDL usable from withing other applications without the risk of RBDL killing the process, when something like reading a file goes wrong.

This was done by creating an RBDLError class (subclass of std::exception) from which more specific error types may be derived. Instead of aborting an error is thrown. When interfacing with RBDL and calling functions, that may lead to errors it is sufficient to catch the error base class, to handle all types of errors.

There are still places in the code where abort() is called, most notably in the examples since those are standalone applications, this also applies to the benchmarking application. Another exception is the SimpleMath part of RBDL since giving it RBDL error handling didn't seam right since it is somewhat separate from RBDL.

### CODE REVIEW

**Comment by mjhmilla** [comment]
Nice work! Once my rush for the upcoming conference is over I'll take a
look at this.

**Comment by ju6ge** [comment]
This pull request has conflicts, with idc-fix and constraint polymorphism, so I will update it so that it can be merged after the constrain polymorphism code has been merged to master. Also I think we should raise the RBDL Version after adding Constraint Polymorphism and Error Handling to RBDL!

**Comment by ju6ge** [comment]
This pull request is now based on the constraint polymorphism branch. 

@mjhmilla Please take a look at the error handling classes and the parts related to your polymorphism code, it might be useful to derive a error class for constraint errors, but i would like your opinion on this first. The luamodel part should only throw file relate errors since we are reading a luafile.

**Comment by mjhmilla** [comment]
I've done the following tasks in this review:

- Compiled & run tests in release & debug mode
- Compared benchmark times in release mode to current rbdl 
- Run clang static-analyzer on both the release and debug versions
- Looked at rbdl_errors.h and rbdl_errors.cc

The code is in good shape and is needed - Thank you very much Felix for adding this. There are some small things to do that will add value to the code:

Code Formatting:
x. No line of code should exceed 80 chars - several do in rbdl_errors.h
x. Each tab should be 2 spaces. Both rbdl_errors.cc & rbdl_errors.h are indented with actual tabs.

Test code:
x. Please add some test code. The test code only needs to illustrate that an error will indeed throw an RBDL error (if it is not thrown a CHECK(false) should be hit), and that the type of the error is correct. Ideally this would include try and catches around each of the RBDL error types, and there would be a CHECK called to make sure that the type of error matches what you expect.

Documentation
x. Please add some concise doxygen in rbdl_errors.h and make sure that the doxygen looks good when compiled. Each error type should be documented so that a niave API programmer can figure out when to use each error. This can be as little as a sentence with a pointer to a spot in the code base where each error type is potentially thrown. Ideally the main RBDLError class would also mention that additional error types can be easily added.

Extra (optional):
x. Please add a short example (in the examples folder) that illustrates the use of a try ... catch around an RBDL function that is called in such a way to throw an error.

**Comment by ju6ge** [comment]
I updated the PR, to include Tests, Documentation and fixed the formatting.

**Comment by mjhmilla** [comment]
I've looked at the updates, re-built the code (in both debug/release), and run the tests. All looks good.

**Pull request merged**
