### PR TITLE
Balance addon

### PR DESCRIPTION
**Pull request by mjhmilla**
This contains the beginnings of a balance addon with an implementation of the 3D FPE complete with the optional calculation of sensitivities, detailed doxygen, and numerical test cases. There are two tests cases included:

- A comparison to a full numerical solution produced from a reference implementation.
- A detailed check of the calculation of the COM and the moment of inertia about the COM using model, which, by construction these two properties are known exactly

There are obvious extensions to add to this addon:
1. The extrapolated COM + sensitivity information 
2. Python wrapping.

### CODE REVIEW

**Comment by ju6ge** [comment]
Hey just a quick note … if you want the balance test to be added to the jenkins pipeline you only need to update the Jenkinfile within the project root. It contains directives to run the tests and save the results, as well as importing the results at the end into the test overview page.

```
 stage('Test RBDL') {   
              steps {         
                dir(path: 'build') {
                  sh './tests/rbdl_tests -r junit &gt; results_rbdl.xml
                  sh './addons/geometry/tests/geometry_tests -r junit &gt; results_geometry.xml'
                  sh './addons/muscle/tests/muscle_tests -r junit -o ./results_muscle.xml
                  sh './addons/luamodel/tests/luamodel_tests -r junit &gt; results_luamodel.xml
                }
                dir(path: 'build/python') {
                  sh './test_rbdlmuscle.py -v'
                  sh './test_wrapper.py -v'
                }     
              }
           }
          post {
            always {
              junit 'build/results_rbdl.xml'
              junit 'build/results_geometry.xml'
              junit 'build/results_muscle.xml'
              junit 'build/results_luamodel.xml'
            }
          }```

**Comment by mjhmilla** [comment]
Thanks Felix - I've just updated the Jenkins file to build RBDL with the balance addon and to run the test. As a note, Felix Aller would be a potential reviewer for this addon. I looked around for him on the list but couldn't find him on the list - I'll ping him over slack.

**Comment by ju6ge** [comment]
Great, I can add Felix Aller to the ORB Github organisation, I would need his Github username or his email address he used to register on Github for that ;)

**Comment by mjhmilla** [comment]
Felix Aller's github handle is: @flxalr

**Review by ju6ge — APPROVED** [review]
From my side this PR look fine and I will merge it. 
- One thing to improve would be adding the DLL Marcos to enable Windows support, but since not many people need that I don't see a reason to delay the merge further and also some other addons are missing that as well. 
- Another thing would be adding support for the casadi backend, by adding the addon to the casadi cmake files, but other addons are also missing that.

**Pull request merged**
